# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Andreea/Downloads/NexysA7_test_env.xdc

# IP: ip/fp_abs/fp_abs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_abs || ORIG_REF_NAME==fp_abs} -quiet] -quiet
