# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andreea/proiect_finn/output_ip_hardware_cu_maimulteepoici/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/design_1/bd/finn_design_inst_0/ip/finn_design_inst_0_MVAU_hls_0_0/finn_design_inst_0_MVAU_hls_0_0.xci
# IP: The module: 'finn_design_inst_0_MVAU_hls_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andreea/proiect_finn/output_ip_hardware_cu_maimulteepoici/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/design_1/bd/finn_design_inst_0/ip/finn_design_inst_0_MVAU_hls_0_0/constraints/MVAU_hls_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_inst_0_MVAU_hls_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/andreea/proiect_finn/output_ip_hardware_cu_maimulteepoici/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/design_1/bd/finn_design_inst_0/ip/finn_design_inst_0_MVAU_hls_0_0/finn_design_inst_0_MVAU_hls_0_0.xci
# IP: The module: 'finn_design_inst_0_MVAU_hls_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andreea/proiect_finn/output_ip_hardware_cu_maimulteepoici/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/design_1/bd/finn_design_inst_0/ip/finn_design_inst_0_MVAU_hls_0_0/constraints/MVAU_hls_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'finn_design_inst_0_MVAU_hls_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
