# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/finn_design/finn_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design || ORIG_REF_NAME==finn_design} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_0_0/finn_design_StreamingFIFO_rtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_0_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_FMPadding_rtl_0_0/finn_design_FMPadding_rtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_FMPadding_rtl_0_0 || ORIG_REF_NAME==finn_design_FMPadding_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_0 || ORIG_REF_NAME==finn_design_fifo_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_ConvolutionInputGenerator_rtl_0_0/finn_design_ConvolutionInputGenerator_rtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_ConvolutionInputGenerator_rtl_0_0 || ORIG_REF_NAME==finn_design_ConvolutionInputGenerator_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_1/finn_design_fifo_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_1 || ORIG_REF_NAME==finn_design_fifo_1} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_0_0/finn_design_StreamingDataWidthConverter_rtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_0_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_2/finn_design_fifo_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_2 || ORIG_REF_NAME==finn_design_fifo_2} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_0_0/finn_design_MVAU_hls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_0_0 || ORIG_REF_NAME==finn_design_MVAU_hls_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_0_wstrm_0/finn_design_MVAU_hls_0_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_0_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_hls_0_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_4_0/finn_design_StreamingFIFO_rtl_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_4_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_4_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_1_0/finn_design_StreamingDataWidthConverter_rtl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_1_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_5_0/finn_design_StreamingFIFO_rtl_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_5_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_5_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingMaxPool_hls_0_0/finn_design_StreamingMaxPool_hls_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingMaxPool_hls_0_0 || ORIG_REF_NAME==finn_design_StreamingMaxPool_hls_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_6_0/finn_design_StreamingFIFO_rtl_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_6_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_6_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_2_0/finn_design_StreamingDataWidthConverter_rtl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_2_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_2_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_7_0/finn_design_StreamingFIFO_rtl_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_7_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_7_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_1_0/finn_design_MVAU_hls_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_1_0 || ORIG_REF_NAME==finn_design_MVAU_hls_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_1_wstrm_0/finn_design_MVAU_hls_1_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_1_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_hls_1_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_8_0/finn_design_StreamingFIFO_rtl_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_8_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_8_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_rtl_0_0/finn_design_MVAU_rtl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_rtl_0_0 || ORIG_REF_NAME==finn_design_MVAU_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_rtl_0_wstrm_0/finn_design_MVAU_rtl_0_wstrm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_rtl_0_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_rtl_0_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_9_0/finn_design_StreamingFIFO_rtl_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_9_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_9_0} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_finn_design_wrapper_0_0/design_1_finn_design_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_finn_design_wrapper_0_0 || ORIG_REF_NAME==design_1_finn_design_wrapper_0_0} -quiet] -quiet

# Block Designs: bd/finn_design/finn_design.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design || ORIG_REF_NAME==finn_design} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_0_0/finn_design_StreamingFIFO_rtl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_0_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_FMPadding_rtl_0_0/finn_design_FMPadding_rtl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_FMPadding_rtl_0_0 || ORIG_REF_NAME==finn_design_FMPadding_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_0/finn_design_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_0 || ORIG_REF_NAME==finn_design_fifo_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_ConvolutionInputGenerator_rtl_0_0/finn_design_ConvolutionInputGenerator_rtl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_ConvolutionInputGenerator_rtl_0_0 || ORIG_REF_NAME==finn_design_ConvolutionInputGenerator_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_1/finn_design_fifo_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_1 || ORIG_REF_NAME==finn_design_fifo_1} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_0_0/finn_design_StreamingDataWidthConverter_rtl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_0_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_fifo_2/finn_design_fifo_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_fifo_2 || ORIG_REF_NAME==finn_design_fifo_2} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_0_0/finn_design_MVAU_hls_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_0_0 || ORIG_REF_NAME==finn_design_MVAU_hls_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_0_wstrm_0/finn_design_MVAU_hls_0_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_0_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_hls_0_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_4_0/finn_design_StreamingFIFO_rtl_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_4_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_4_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_1_0/finn_design_StreamingDataWidthConverter_rtl_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_1_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_5_0/finn_design_StreamingFIFO_rtl_5_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_5_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_5_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingMaxPool_hls_0_0/finn_design_StreamingMaxPool_hls_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingMaxPool_hls_0_0 || ORIG_REF_NAME==finn_design_StreamingMaxPool_hls_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_6_0/finn_design_StreamingFIFO_rtl_6_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_6_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_6_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingDataWidthConverter_rtl_2_0/finn_design_StreamingDataWidthConverter_rtl_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingDataWidthConverter_rtl_2_0 || ORIG_REF_NAME==finn_design_StreamingDataWidthConverter_rtl_2_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_7_0/finn_design_StreamingFIFO_rtl_7_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_7_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_7_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_1_0/finn_design_MVAU_hls_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_1_0 || ORIG_REF_NAME==finn_design_MVAU_hls_1_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_hls_1_wstrm_0/finn_design_MVAU_hls_1_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_hls_1_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_hls_1_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_8_0/finn_design_StreamingFIFO_rtl_8_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_8_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_8_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_rtl_0_0/finn_design_MVAU_rtl_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_rtl_0_0 || ORIG_REF_NAME==finn_design_MVAU_rtl_0_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_MVAU_rtl_0_wstrm_0/finn_design_MVAU_rtl_0_wstrm_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_MVAU_rtl_0_wstrm_0 || ORIG_REF_NAME==finn_design_MVAU_rtl_0_wstrm_0} -quiet] -quiet

# IP: bd/finn_design/ip/finn_design_StreamingFIFO_rtl_9_0/finn_design_StreamingFIFO_rtl_9_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==finn_design_StreamingFIFO_rtl_9_0 || ORIG_REF_NAME==finn_design_StreamingFIFO_rtl_9_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: /home/andreea/proiect_finn/output_ip_hardware_cu_argmax/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/finn_design_ooc.xdc

# XDC: /home/andreea/proiect_finn/output_ip_hardware_cu_argmax/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/finn_design/finn_design_ooc.xdc

# XDC: /home/andreea/proiect_finn/output_ip_hardware_cu_argmax/stitched_ip/finn_vivado_stitch_proj.gen/sources_1/bd/design_1/design_1_ooc.xdc
